version: '3'
services:
    # PHP Service
    enthusiart:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: enthusiart
        restart: unless-stopped
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
        networks:
            - linux_gaboot
        volumes:
            - .:/var/www/html
        ports:
            - 9000:9000
    nginx:
        image: nginx:latest
        container_name: enthusiart-nginx
        restart: unless-stopped
        ports:
            - 8143:8143
        volumes:
            - .:/var/www/html
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - linux_gaboot
        depends_on:
            - enthusiart
networks:
    linux_gaboot:
        external: true
